//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class usign
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string userName { get; set; }
        public string Password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public decimal Phone { get; set; }
        public string profile { get; set; }
        public string LinkedinURL { get; set; }
        public Nullable<int> YOE { get; set; }
        public Nullable<bool> resetPassword { get; set; }
        public string pictureUrl { get; set; }
        public bool active { get; set; }
        public int role { get; set; }
        public string regCode { get; set; }
        public string TrainerTimings { get; set; }
        public string TrainerTechnology { get; set; }
    }
}
